INSERT INTO tools (
  slug,
  name,
  description,
  category,
  type,
  provider,
  icon,
  requires_auth,
  auth_type,
  auth_provider,
  capabilities,
  use_cases,
  permissions,
  approval_rules,
  config,
  risk_level,
  can_read,
  can_write,
  can_delete,
  can_execute,
  enabled
)
VALUES
(
  'serp_search',
  'SERP Search',
  'Search the web and retrieve structured search results.',
  'search',
  'api',
  'SerpAPI',
  'https://ik.imagekit.io/Tubeguruji/logos/serpapi.png',
  FALSE,
  'api_key',
  NULL,
  '["google_search","news_search","images_search","shopping_search"]'::jsonb,
  '["Search web content","Find recent news","Extract search snippets"]'::jsonb,
  '[]'::jsonb,
  '{"search":false}'::jsonb,
  '{"envKey":"SERP_API_KEY"}'::jsonb,
  'low',
  TRUE,
  FALSE,
  FALSE,
  TRUE,
  TRUE
),
(
  'web_search',
  'Web Search',
  'Search public web information and discover useful sources.',
  'search',
  'native',
  'Google',
  'https://ik.imagekit.io/Tubeguruji/logos/web-link.png',
  FALSE,
  'none',
  NULL,
  '["web_search","research","fact_lookup","recent_information"]'::jsonb,
  '["Research current topics","Find recent information","Verify facts","Discover sources"]'::jsonb,
  '[]'::jsonb,
  '{"search":false}'::jsonb,
  NULL,
  'low',
  TRUE,
  FALSE,
  FALSE,
  TRUE,
  TRUE
),
(
  'browserbase',
  'Browserbase',
  'Navigate websites, interact with pages and extract information.',
  'browser',
  'api',
  'Browserbase',
  'https://ik.imagekit.io/Tubeguruji/logos/browserbase.png',
  FALSE,
  'api_key',
  NULL,
  '["open_page","navigate","click","type","extract_content","browser_automation","authenticated_browsing"]'::jsonb,
  '["Visit websites","Extract data","Navigate dashboards","Fill forms","Perform multi-step browser tasks"]'::jsonb,
  '[]'::jsonb,
  '{"navigate":false,"extract":false,"fillForm":true,"submitForm":true}'::jsonb,
  '{"envKey":"BROWSERBASE_API_KEY"}'::jsonb,
  'high',
  TRUE,
  TRUE,
  FALSE,
  TRUE,
  TRUE
),
(
  'gmail',
  'Gmail',
  'Search, read, draft and send Gmail messages.',
  'communication',
  'mcp',
  'Google',
  'https://ik.imagekit.io/Tubeguruji/logos/gmail.webp',
  TRUE,
  'oauth',
  'google',
  '["search_email","read_email","read_threads","create_draft","send_email","manage_labels"]'::jsonb,
  '["Summarize emails","Find important emails","Draft replies","Send reports","Monitor inbox"]'::jsonb,
  '[]'::jsonb,
  '{"search":false,"read":false,"draft":false,"send":true,"delete":true}'::jsonb,
  NULL,
  'high',
  TRUE,
  TRUE,
  FALSE,
  TRUE,
  TRUE
),
(
  'slack',
  'Slack',
  'Search, read and send messages in Slack channels.',
  'communication',
  'mcp',
  'Slack',
  'https://ik.imagekit.io/Tubeguruji/logos/slack.png',
  TRUE,
  'oauth',
  'slack',
  '["search_messages","read_messages","read_channels","send_message"]'::jsonb,
  '["Summarize team conversations","Find important messages","Send notifications","Post agent reports"]'::jsonb,
  '[]'::jsonb,
  '{"read":false,"send":true}'::jsonb,
  NULL,
  'high',
  TRUE,
  TRUE,
  FALSE,
  TRUE,
  TRUE
),
(
  'notion',
  'Notion',
  'Search, read and update pages and databases in Notion.',
  'productivity',
  'mcp',
  'Notion',
  'https://ik.imagekit.io/Tubeguruji/logos/notion.png',
  TRUE,
  'oauth',
  'notion',
  '["search_pages","read_page","create_page","update_page","query_database"]'::jsonb,
  '["Save research","Create notes","Update project trackers","Search docs"]'::jsonb,
  '[]'::jsonb,
  '{"read":false,"create":false,"update":true}'::jsonb,
  NULL,
  'medium',
  TRUE,
  TRUE,
  TRUE,
  TRUE,
  TRUE
),
(
  'github',
  'GitHub',
  'Read repositories, issues and pull requests and perform repository actions.',
  'developer',
  'mcp',
  'GitHub',
  'https://ik.imagekit.io/Tubeguruji/logos/github.svg',
  TRUE,
  'oauth',
  'github',
  '["read_repository","search_code","read_issues","create_issue","read_pull_requests","create_pull_request"]'::jsonb,
  '["Analyze repositories","Find code","Review issues","Create issues","Work with pull requests"]'::jsonb,
  '[]'::jsonb,
  '{"read":false,"create_issue":true,"create_pull_request":true,"merge":true,"delete":true}'::jsonb,
  NULL,
  'high',
  TRUE,
  TRUE,
  TRUE,
  TRUE,
  TRUE
)
ON CONFLICT (slug)
DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  type = EXCLUDED.type,
  provider = EXCLUDED.provider,
  icon = EXCLUDED.icon,
  requires_auth = EXCLUDED.requires_auth,
  auth_type = EXCLUDED.auth_type,
  auth_provider = EXCLUDED.auth_provider,
  capabilities = EXCLUDED.capabilities,
  use_cases = EXCLUDED.use_cases,
  permissions = EXCLUDED.permissions,
  approval_rules = EXCLUDED.approval_rules,
  config = EXCLUDED.config,
  risk_level = EXCLUDED.risk_level,
  can_read = EXCLUDED.can_read,
  can_write = EXCLUDED.can_write,
  can_delete = EXCLUDED.can_delete,
  can_execute = EXCLUDED.can_execute,
  enabled = EXCLUDED.enabled,
  updated_at = NOW();
